import type {
  Category,
  FetchProductsParams,
  PaginatedProducts,
  Product,
  PublicUser,
  Wishlist,
} from "./types";

// =====================================================================
//  Data layer for Wishlist MVP.
//
//  Для подключения реальных API замени fetchMockProducts() на вызов
//  Ozon/WB/Я.Маркет Affiliate API. Интерфейс Product уже типизирован под
//  реальные ответы (title, category, price, currency, store, image, url,
//  rating, inStock).
//
//  Ожидаемый контракт реального endpoint:
//      GET /affiliate/v1/products?query=...&category=...&page=1&pageSize=20
//      -> { items: Product[], total: number, page, pageSize, totalPages }
//
//  Цены соответствуют российскому рынку 2024–2025.
// =====================================================================

const unsplash = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=70`;

export const PRODUCTS: Product[] = [
  // --- Электроника ---
  {
    id: "p-001",
    title: "Apple iPhone 15 128GB",
    category: "Электроника",
    price: 89990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1592286130474-79dc83ff4d9b"),
    url: "https://market.yandex.ru/product/iphone-15",
    rating: 4.8,
    inStock: true,
    description: "Смартфон с чипом A16 Bionic и системой камер нового поколения.",
  },
  {
    id: "p-002",
    title: "Apple AirPods Pro 2",
    category: "Электроника",
    price: 14500,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1600294037681-c80b4cb5b434"),
    url: "https://ozon.ru/product/airpods-pro-2",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-003",
    title: "Sony WH-1000XM5",
    category: "Электроника",
    price: 32990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1518441902113-c1d3f0f1f7f3"),
    url: "https://dns-shop.ru/product/sony-wh-1000xm5",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-004",
    title: "Samsung Galaxy S24 256GB",
    category: "Электроника",
    price: 79990,
    currency: "RUB",
    store: "М.Видео",
    image: unsplash("1511707171634-5f897ff02aa9"),
    url: "https://mvideo.ru/product/galaxy-s24",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-005",
    title: "Apple MacBook Air 13 M3",
    category: "Электроника",
    price: 119990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1517336714731-489689fd1ca8"),
    url: "https://market.yandex.ru/product/macbook-air-m3",
    rating: 4.9,
    inStock: false,
  },
  {
    id: "p-006",
    title: "Apple iPad 10.9 64GB",
    category: "Электроника",
    price: 42990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1585155770447-2f66e2a397b5"),
    url: "https://ozon.ru/product/ipad-10",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-007",
    title: "Apple Watch Series 9 41mm",
    category: "Электроника",
    price: 37990,
    currency: "RUB",
    store: "М.Видео",
    image: unsplash("1546868871-7041f2a55e12"),
    url: "https://mvideo.ru/product/apple-watch-s9",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-008",
    title: "Яндекс Станция Миди",
    category: "Электроника",
    price: 17990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1558089687-f282ffcbc126"),
    url: "https://market.yandex.ru/product/station-midi",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p-009",
    title: "Xiaomi Mi Band 8",
    category: "Электроника",
    price: 3490,
    currency: "RUB",
    store: "WB",
    image: unsplash("1579586337278-3befd40fd17a"),
    url: "https://wildberries.ru/catalog/mi-band-8",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p-010",
    title: "Kindle Paperwhite 11 16GB",
    category: "Электроника",
    price: 18990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1519682337058-a94d519337bc"),
    url: "https://ozon.ru/product/kindle-paperwhite-11",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-011",
    title: "Sony PlayStation 5 Slim",
    category: "Электроника",
    price: 54990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1606813907291-d86efa9b94db"),
    url: "https://dns-shop.ru/product/ps5-slim",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-012",
    title: "Nintendo Switch OLED",
    category: "Электроника",
    price: 32990,
    currency: "RUB",
    store: "М.Видео",
    image: unsplash("1605901309584-818e25960a8f"),
    url: "https://mvideo.ru/product/switch-oled",
    rating: 4.8,
    inStock: false,
  },
  {
    id: "p-013",
    title: "Беспроводная мышь Logitech MX Master 3S",
    category: "Электроника",
    price: 9990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1527864550417-7fd91fc51a46"),
    url: "https://dns-shop.ru/product/mx-master-3s",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-014",
    title: "Клавиатура Keychron K2 Pro",
    category: "Электроника",
    price: 12990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1587829741301-dc798b83add3"),
    url: "https://ozon.ru/product/keychron-k2-pro",
    rating: 4.7,
    inStock: true,
  },

  // --- Одежда ---
  {
    id: "p-015",
    title: "Кроссовки Nike Air Max 97",
    category: "Одежда",
    price: 12000,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1542291026-7eec264c27ff"),
    url: "https://lamoda.ru/p/air-max-97",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-016",
    title: "Кроссовки Adidas Samba OG",
    category: "Одежда",
    price: 11500,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1600269452121-4f2416e55c28"),
    url: "https://lamoda.ru/p/samba-og",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-017",
    title: "Худи Uniqlo U Oversized",
    category: "Одежда",
    price: 4990,
    currency: "RUB",
    store: "WB",
    image: unsplash("1556821840-3a63f95609a7"),
    url: "https://wildberries.ru/catalog/uniqlo-hoodie",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-018",
    title: "Джинсы Levi's 501 Original",
    category: "Одежда",
    price: 8990,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1542272604-787c3835535d"),
    url: "https://lamoda.ru/p/levis-501",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-019",
    title: "Куртка пуховик Uniqlo Ultra Light",
    category: "Одежда",
    price: 6990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1551028719-00167b16eac5"),
    url: "https://ozon.ru/product/uniqlo-ultra-light",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-020",
    title: "Футболка Carhartt WIP Pocket",
    category: "Одежда",
    price: 3890,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1583743814966-8936f5b7be1a"),
    url: "https://lamoda.ru/p/carhartt-tee",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-021",
    title: "Шапка The North Face",
    category: "Одежда",
    price: 2490,
    currency: "RUB",
    store: "WB",
    image: unsplash("1520975916090-3105956dac38"),
    url: "https://wildberries.ru/catalog/tnf-beanie",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p-022",
    title: "Рюкзак Herschel Little America",
    category: "Одежда",
    price: 8490,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1553062407-98eeb64c6a62"),
    url: "https://ozon.ru/product/herschel-backpack",
    rating: 4.7,
    inStock: true,
  },

  // --- Книги ---
  {
    id: "p-023",
    title: "Виктор Пелевин — «Transhumanism Inc.»",
    category: "Книги",
    price: 790,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1544947950-fa07a98d237f"),
    url: "https://ozon.ru/product/transhumanism-inc",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "p-024",
    title: "Харуки Мураками — «Норвежский лес»",
    category: "Книги",
    price: 680,
    currency: "RUB",
    store: "WB",
    image: unsplash("1512820790803-83ca734da794"),
    url: "https://wildberries.ru/catalog/norwegian-wood",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-025",
    title: "Роберт Мартин — «Чистый код»",
    category: "Книги",
    price: 1190,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1516979187457-637abb4f9353"),
    url: "https://market.yandex.ru/product/clean-code",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-026",
    title: "Д. Канеман — «Думай медленно… решай быстро»",
    category: "Книги",
    price: 890,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1495446815901-a7297e633e8d"),
    url: "https://ozon.ru/product/thinking-fast-slow",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-027",
    title: "Дж. Оруэлл — «1984»",
    category: "Книги",
    price: 620,
    currency: "RUB",
    store: "WB",
    image: unsplash("1524995997946-a1c2e315a42f"),
    url: "https://wildberries.ru/catalog/1984",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-028",
    title: "А. Камю — «Посторонний»",
    category: "Книги",
    price: 560,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1509266272358-7701da638078"),
    url: "https://ozon.ru/product/stranger",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-029",
    title: "Атомные привычки — Джеймс Клир",
    category: "Книги",
    price: 950,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1528459801416-a9e53bbf4e17"),
    url: "https://market.yandex.ru/product/atomic-habits",
    rating: 4.8,
    inStock: true,
  },

  // --- Дом ---
  {
    id: "p-030",
    title: "Ароматическая свеча Yankee Candle",
    category: "Дом",
    price: 1990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1603006905003-be475563bc59"),
    url: "https://ozon.ru/product/yankee-candle",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-031",
    title: "Плед из микрофибры IKEA POLARVIDE",
    category: "Дом",
    price: 1290,
    currency: "RUB",
    store: "WB",
    image: unsplash("1519710164239-da123dc03ef4"),
    url: "https://wildberries.ru/catalog/polarvide",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-032",
    title: "Кофемашина De'Longhi Magnifica",
    category: "Дом",
    price: 52990,
    currency: "RUB",
    store: "М.Видео",
    image: unsplash("1498804103079-a6351b050096"),
    url: "https://mvideo.ru/product/magnifica",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-033",
    title: "Чайник электрический Bork",
    category: "Дом",
    price: 9990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1517686469429-8bdb88b9f907"),
    url: "https://dns-shop.ru/product/bork-kettle",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p-034",
    title: "Постельное бельё сатин 2‑спальное",
    category: "Дом",
    price: 3490,
    currency: "RUB",
    store: "WB",
    image: unsplash("1505691938895-1758d7feb511"),
    url: "https://wildberries.ru/catalog/sateen-set",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-035",
    title: "Настольная лампа Xiaomi Mi LED",
    category: "Дом",
    price: 2990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1507473885765-e6ed057f782c"),
    url: "https://ozon.ru/product/mi-led-desk",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-036",
    title: "Диффузор ZARA HOME Rosewood",
    category: "Дом",
    price: 2490,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1600857544200-b2f666a9a2ec"),
    url: "https://lamoda.ru/p/rosewood-diffuser",
    rating: 4.6,
    inStock: true,
  },

  // --- Хобби ---
  {
    id: "p-037",
    title: "Набор акварельных красок Van Gogh 24",
    category: "Хобби",
    price: 4590,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1513364776144-60967b0f800f"),
    url: "https://ozon.ru/product/van-gogh-24",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-038",
    title: "Пазл Ravensburger 1500 деталей",
    category: "Хобби",
    price: 3290,
    currency: "RUB",
    store: "WB",
    image: unsplash("1606216794074-735e91aa2c92"),
    url: "https://wildberries.ru/catalog/ravensburger-1500",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-039",
    title: "Гитара Yamaha F310",
    category: "Хобби",
    price: 14990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1510915361894-db8b7855a8a8"),
    url: "https://market.yandex.ru/product/yamaha-f310",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-040",
    title: "Конструктор LEGO Botanical Roses",
    category: "Хобби",
    price: 4990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1587654780291-39c9404d746b"),
    url: "https://ozon.ru/product/lego-roses",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-041",
    title: "Набор для каллиграфии Pilot Parallel",
    category: "Хобби",
    price: 2890,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1455390582262-044cdead277a"),
    url: "https://ozon.ru/product/pilot-parallel",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-042",
    title: "Фотоаппарат моментальной печати Instax Mini 12",
    category: "Хобби",
    price: 7990,
    currency: "RUB",
    store: "М.Видео",
    image: unsplash("1519183071298-a2962be96d7e"),
    url: "https://mvideo.ru/product/instax-mini-12",
    rating: 4.7,
    inStock: true,
  },

  // --- Красота ---
  {
    id: "p-043",
    title: "Парфюм Maison Margiela Replica — By the Fireplace",
    category: "Красота",
    price: 12990,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1541643600914-78b084683601"),
    url: "https://lamoda.ru/p/replica-fireplace",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-044",
    title: "Крем для лица La Roche-Posay Toleriane",
    category: "Красота",
    price: 1890,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1556228578-dd3a3e8e5b10"),
    url: "https://ozon.ru/product/toleriane",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-045",
    title: "Фен Dyson Supersonic",
    category: "Красота",
    price: 49990,
    currency: "RUB",
    store: "М.Видео",
    image: unsplash("1522338140262-f46f5913618a"),
    url: "https://mvideo.ru/product/dyson-supersonic",
    rating: 4.9,
    inStock: false,
  },
  {
    id: "p-046",
    title: "Набор кистей Real Techniques Everyday",
    category: "Красота",
    price: 1590,
    currency: "RUB",
    store: "WB",
    image: unsplash("1522335789203-aaa5d0d9d9a0"),
    url: "https://wildberries.ru/catalog/real-techniques",
    rating: 4.6,
    inStock: true,
  },

  // --- Спорт ---
  {
    id: "p-047",
    title: "Коврик для йоги Manduka PRO",
    category: "Спорт",
    price: 9990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1517344884509-a0c97ec11bcc"),
    url: "https://ozon.ru/product/manduka-pro",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-048",
    title: "Гантели разборные 20 кг",
    category: "Спорт",
    price: 6490,
    currency: "RUB",
    store: "WB",
    image: unsplash("1517838277536-f5f99be501cd"),
    url: "https://wildberries.ru/catalog/dumbbells-20",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-049",
    title: "Фитнес-браслет Garmin Vivosmart 5",
    category: "Спорт",
    price: 16990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1516569422572-4f5d5b2b7b2b"),
    url: "https://dns-shop.ru/product/vivosmart-5",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-050",
    title: "Велосипед Merida Big Nine 20",
    category: "Спорт",
    price: 59990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1511751918988-0c17a3a7a4b0"),
    url: "https://market.yandex.ru/product/big-nine-20",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-051",
    title: "Скакалка скоростная RDX",
    category: "Спорт",
    price: 990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1518611012118-696072aa579a"),
    url: "https://ozon.ru/product/rdx-skipping-rope",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p-052",
    title: "Ролик для пресса Reebok",
    category: "Спорт",
    price: 2490,
    currency: "RUB",
    store: "WB",
    image: unsplash("1599058917212-d750089bc07e"),
    url: "https://wildberries.ru/catalog/reebok-ab-roller",
    rating: 4.6,
    inStock: true,
  },

  // --- Детям ---
  {
    id: "p-053",
    title: "Конструктор LEGO Classic 11030",
    category: "Детям",
    price: 3990,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1596461404969-9ae70f2830c1"),
    url: "https://ozon.ru/product/lego-classic-11030",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-054",
    title: "Мягкая игрушка Jellycat Bashful Bunny",
    category: "Детям",
    price: 3490,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1503602642458-232111445657"),
    url: "https://lamoda.ru/p/jellycat-bunny",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-055",
    title: "Самокат Micro Mini Deluxe",
    category: "Детям",
    price: 11990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1511994298241-608e28f14fde"),
    url: "https://market.yandex.ru/product/micro-mini",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-056",
    title: "Настольная игра Каркассон",
    category: "Детям",
    price: 2890,
    currency: "RUB",
    store: "WB",
    image: unsplash("1606503153255-59d8b8b2f3b7"),
    url: "https://wildberries.ru/catalog/carcassonne",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-057",
    title: "Развивающий центр Fisher-Price",
    category: "Детям",
    price: 4890,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1603791440384-56cd371ee9a7"),
    url: "https://ozon.ru/product/fisher-price",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-058",
    title: "Набор для лепки Play-Doh Kitchen",
    category: "Детям",
    price: 1890,
    currency: "RUB",
    store: "WB",
    image: unsplash("1596464716127-f2a82984de30"),
    url: "https://wildberries.ru/catalog/play-doh-kitchen",
    rating: 4.6,
    inStock: true,
  },

  // --- Дополнительно ---
  {
    id: "p-059",
    title: "Колонка JBL Charge 5",
    category: "Электроника",
    price: 14990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1608043152269-423dbba4e7e1"),
    url: "https://dns-shop.ru/product/jbl-charge-5",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p-060",
    title: "Термос Stanley Classic 1L",
    category: "Дом",
    price: 3490,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1519681393784-d120267933ba"),
    url: "https://ozon.ru/product/stanley-classic",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-061",
    title: "Рюкзак Peak Design Everyday V2",
    category: "Одежда",
    price: 21990,
    currency: "RUB",
    store: "Я.Маркет",
    image: unsplash("1548036328-c9fa89d128fa"),
    url: "https://market.yandex.ru/product/peak-design",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "p-062",
    title: "Массажный пистолет Xiaomi Mijia",
    category: "Спорт",
    price: 6490,
    currency: "RUB",
    store: "Ozon",
    image: unsplash("1571019613454-1cb2f99b2d8b"),
    url: "https://ozon.ru/product/mijia-massage-gun",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p-063",
    title: "Подарочный набор чая Kusmi Tea",
    category: "Дом",
    price: 3990,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1576092768241-dec231879fc3"),
    url: "https://lamoda.ru/p/kusmi-tea",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p-064",
    title: "Парфюм Tom Ford Lost Cherry 50ml",
    category: "Красота",
    price: 34990,
    currency: "RUB",
    store: "Lamoda",
    image: unsplash("1541643600914-78b084683601"),
    url: "https://lamoda.ru/p/lost-cherry",
    rating: 4.9,
    inStock: false,
  },
  {
    id: "p-065",
    title: "Wacom One by Wacom S",
    category: "Хобби",
    price: 5990,
    currency: "RUB",
    store: "ДНС",
    image: unsplash("1527443224154-c4a3942d3acf"),
    url: "https://dns-shop.ru/product/wacom-one-s",
    rating: 4.6,
    inStock: true,
  },
];

export const CATEGORIES: Category[] = [
  "Электроника",
  "Одежда",
  "Книги",
  "Дом",
  "Хобби",
  "Красота",
  "Спорт",
  "Детям",
];

// ------------------------------------------------------------
// Mock пользователей и вишлистов (используются на странице /friends
// и /wishlist/[id] — заменяются на Prisma-запросы после добавления Auth).
// ------------------------------------------------------------

export const MOCK_USERS: PublicUser[] = [
  {
    id: "u-anna",
    username: "anna",
    name: "Анна Соколова",
    email: "anna@wishlist.app",
    avatarUrl: "https://i.pravatar.cc/160?img=47",
    bio: "Дизайнер. Люблю книги и ароматы.",
    followers: 124,
    wishlists: 3,
  },
  {
    id: "u-mark",
    username: "mark",
    name: "Марк Петров",
    email: "mark@wishlist.app",
    avatarUrl: "https://i.pravatar.cc/160?img=12",
    bio: "Фронтендер, коллекционер клавиатур.",
    followers: 58,
    wishlists: 2,
  },
  {
    id: "u-lena",
    username: "lena",
    name: "Лена Иванова",
    email: "lena@wishlist.app",
    avatarUrl: "https://i.pravatar.cc/160?img=32",
    bio: "Бегу марафоны и пью кофе.",
    followers: 210,
    wishlists: 4,
  },
  {
    id: "u-ivan",
    username: "ivan",
    name: "Иван Смирнов",
    email: "ivan@wishlist.app",
    avatarUrl: "https://i.pravatar.cc/160?img=14",
    bio: "Музыкант, фанат LEGO.",
    followers: 72,
    wishlists: 2,
  },
  {
    id: "u-kate",
    username: "kate",
    name: "Катя Орлова",
    email: "kate@wishlist.app",
    avatarUrl: "https://i.pravatar.cc/160?img=25",
    bio: "Фото, путешествия, кулинария.",
    followers: 186,
    wishlists: 5,
  },
];

const byId = (arr: Product[], id: string) => arr.find((p) => p.id === id)!;

export const MOCK_WISHLISTS: Wishlist[] = [
  {
    id: "w-anna-birthday",
    ownerId: "u-anna",
    title: "День рождения 2025",
    description: "Самые долгожданные вещи к весне.",
    coverUrl: unsplash("1522770179533-24471fcdba45"),
    visibility: "PUBLIC",
    items: [
      {
        id: "i-001",
        wishlistId: "w-anna-birthday",
        title: byId(PRODUCTS, "p-001").title,
        category: "Электроника",
        price: byId(PRODUCTS, "p-001").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-001").store,
        imageUrl: byId(PRODUCTS, "p-001").image,
        url: byId(PRODUCTS, "p-001").url,
        status: "AVAILABLE",
        createdAt: "2025-01-10T10:00:00Z",
      },
      {
        id: "i-002",
        wishlistId: "w-anna-birthday",
        title: byId(PRODUCTS, "p-043").title,
        category: "Красота",
        price: byId(PRODUCTS, "p-043").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-043").store,
        imageUrl: byId(PRODUCTS, "p-043").image,
        url: byId(PRODUCTS, "p-043").url,
        status: "AVAILABLE",
        createdAt: "2025-01-11T10:00:00Z",
      },
      {
        id: "i-003",
        wishlistId: "w-anna-birthday",
        title: byId(PRODUCTS, "p-030").title,
        category: "Дом",
        price: byId(PRODUCTS, "p-030").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-030").store,
        imageUrl: byId(PRODUCTS, "p-030").image,
        url: byId(PRODUCTS, "p-030").url,
        status: "RESERVED",
        createdAt: "2025-01-14T10:00:00Z",
      },
    ],
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-14T10:00:00Z",
  },
  {
    id: "w-mark-setup",
    ownerId: "u-mark",
    title: "Обновление сетапа",
    description: "Клавиатуры, мыши, мониторы.",
    coverUrl: unsplash("1587829741301-dc798b83add3"),
    visibility: "PUBLIC",
    items: [
      {
        id: "i-010",
        wishlistId: "w-mark-setup",
        title: byId(PRODUCTS, "p-014").title,
        category: "Электроника",
        price: byId(PRODUCTS, "p-014").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-014").store,
        imageUrl: byId(PRODUCTS, "p-014").image,
        url: byId(PRODUCTS, "p-014").url,
        status: "AVAILABLE",
        createdAt: "2025-02-01T10:00:00Z",
      },
      {
        id: "i-011",
        wishlistId: "w-mark-setup",
        title: byId(PRODUCTS, "p-013").title,
        category: "Электроника",
        price: byId(PRODUCTS, "p-013").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-013").store,
        imageUrl: byId(PRODUCTS, "p-013").image,
        url: byId(PRODUCTS, "p-013").url,
        status: "AWAITING",
        createdAt: "2025-02-02T10:00:00Z",
      },
    ],
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-02T10:00:00Z",
  },
  {
    id: "w-lena-sport",
    ownerId: "u-lena",
    title: "Экипировка для марафона",
    description: "Готовимся к весеннему старту.",
    coverUrl: unsplash("1517836357463-d25dfeac3438"),
    visibility: "PUBLIC",
    items: [
      {
        id: "i-020",
        wishlistId: "w-lena-sport",
        title: byId(PRODUCTS, "p-015").title,
        category: "Одежда",
        price: byId(PRODUCTS, "p-015").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-015").store,
        imageUrl: byId(PRODUCTS, "p-015").image,
        url: byId(PRODUCTS, "p-015").url,
        status: "AVAILABLE",
        createdAt: "2025-03-01T10:00:00Z",
      },
      {
        id: "i-021",
        wishlistId: "w-lena-sport",
        title: byId(PRODUCTS, "p-049").title,
        category: "Спорт",
        price: byId(PRODUCTS, "p-049").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-049").store,
        imageUrl: byId(PRODUCTS, "p-049").image,
        url: byId(PRODUCTS, "p-049").url,
        status: "AVAILABLE",
        createdAt: "2025-03-03T10:00:00Z",
      },
      {
        id: "i-022",
        wishlistId: "w-lena-sport",
        title: byId(PRODUCTS, "p-047").title,
        category: "Спорт",
        price: byId(PRODUCTS, "p-047").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-047").store,
        imageUrl: byId(PRODUCTS, "p-047").image,
        url: byId(PRODUCTS, "p-047").url,
        status: "RESERVED",
        createdAt: "2025-03-05T10:00:00Z",
      },
    ],
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-03-05T10:00:00Z",
  },
  {
    id: "w-kate-home",
    ownerId: "u-kate",
    title: "Уют в квартире",
    description: "Свечи, пледы, мелочи.",
    coverUrl: unsplash("1484101403633-562f891dc89a"),
    visibility: "PUBLIC",
    items: [
      {
        id: "i-030",
        wishlistId: "w-kate-home",
        title: byId(PRODUCTS, "p-031").title,
        category: "Дом",
        price: byId(PRODUCTS, "p-031").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-031").store,
        imageUrl: byId(PRODUCTS, "p-031").image,
        url: byId(PRODUCTS, "p-031").url,
        status: "AVAILABLE",
        createdAt: "2025-02-11T10:00:00Z",
      },
      {
        id: "i-031",
        wishlistId: "w-kate-home",
        title: byId(PRODUCTS, "p-036").title,
        category: "Дом",
        price: byId(PRODUCTS, "p-036").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-036").store,
        imageUrl: byId(PRODUCTS, "p-036").image,
        url: byId(PRODUCTS, "p-036").url,
        status: "AVAILABLE",
        createdAt: "2025-02-12T10:00:00Z",
      },
    ],
    createdAt: "2025-02-11T10:00:00Z",
    updatedAt: "2025-02-12T10:00:00Z",
  },
  {
    id: "w-ivan-hobby",
    ownerId: "u-ivan",
    title: "Хобби-релакс",
    description: "LEGO и музыка.",
    coverUrl: unsplash("1587654780291-39c9404d746b"),
    visibility: "LINK",
    items: [
      {
        id: "i-040",
        wishlistId: "w-ivan-hobby",
        title: byId(PRODUCTS, "p-040").title,
        category: "Хобби",
        price: byId(PRODUCTS, "p-040").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-040").store,
        imageUrl: byId(PRODUCTS, "p-040").image,
        url: byId(PRODUCTS, "p-040").url,
        status: "AVAILABLE",
        createdAt: "2025-04-01T10:00:00Z",
      },
      {
        id: "i-041",
        wishlistId: "w-ivan-hobby",
        title: byId(PRODUCTS, "p-039").title,
        category: "Хобби",
        price: byId(PRODUCTS, "p-039").price,
        currency: "RUB",
        store: byId(PRODUCTS, "p-039").store,
        imageUrl: byId(PRODUCTS, "p-039").image,
        url: byId(PRODUCTS, "p-039").url,
        status: "AWAITING",
        createdAt: "2025-04-05T10:00:00Z",
      },
    ],
    createdAt: "2025-04-01T10:00:00Z",
    updatedAt: "2025-04-05T10:00:00Z",
  },
];

// =====================================================================
//  Публичное API слоя данных
// =====================================================================

export async function fetchMockProducts(
  params: FetchProductsParams = {},
): Promise<PaginatedProducts> {
  const {
    query = "",
    category = "Все",
    store = "Все",
    minPrice,
    maxPrice,
    inStockOnly = false,
    page = 1,
    pageSize = 12,
    sort = "popular",
  } = params;

  const normalized = query.trim().toLowerCase();

  let filtered = PRODUCTS.filter((p) => {
    if (normalized && !p.title.toLowerCase().includes(normalized)) return false;
    if (category !== "Все" && p.category !== category) return false;
    if (store !== "Все" && p.store !== store) return false;
    if (typeof minPrice === "number" && p.price < minPrice) return false;
    if (typeof maxPrice === "number" && p.price > maxPrice) return false;
    if (inStockOnly && !p.inStock) return false;
    return true;
  });

  filtered = [...filtered].sort((a, b) => {
    switch (sort) {
      case "price-asc":
        return a.price - b.price;
      case "price-desc":
        return b.price - a.price;
      case "rating":
        return b.rating - a.rating;
      case "popular":
      default:
        return b.rating * 10 + (b.inStock ? 1 : 0) - (a.rating * 10 + (a.inStock ? 1 : 0));
    }
  });

  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(Math.max(1, page), totalPages);
  const items = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);

  return { items, total, page: safePage, pageSize, totalPages };
}

export async function getPublicWishlists(): Promise<Wishlist[]> {
  return MOCK_WISHLISTS.filter((w) => w.visibility === "PUBLIC");
}

export async function getWishlistById(id: string): Promise<Wishlist | null> {
  return MOCK_WISHLISTS.find((w) => w.id === id) ?? null;
}

export async function getUserById(id: string): Promise<PublicUser | null> {
  return MOCK_USERS.find((u) => u.id === id) ?? null;
}

export async function searchUsers(term: string): Promise<PublicUser[]> {
  const t = term.trim().toLowerCase();
  if (!t) return MOCK_USERS;
  return MOCK_USERS.filter(
    (u) =>
      u.username.toLowerCase().includes(t) ||
      u.name.toLowerCase().includes(t) ||
      u.email.toLowerCase().includes(t),
  );
}
